name = "file-upload-validator"
main = "src/index.ts"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables for the worker
ENVIRONMENT = "development"